/* GAM Vehicle Editor – Terms & Privacy modal multilingual content */
/* jshint esversion: 5 */

var H4 = 'style="color:#fff;margin:1.5rem 0 0.5rem;"';
var UL = 'style="padding-left:1.25rem;display:flex;flex-direction:column;gap:0.4rem;"';
var EMAIL = '<a href="mailto:support@gam-editor.com" style="color:#60a5fa;">support@gam-editor.com</a>';
var LS_LINK = '<a href="https://www.lemonsqueezy.com" target="_blank" style="color:#60a5fa;">Lemon Squeezy</a>';
var LS_PP   = '<a href="https://www.lemonsqueezy.com/privacy" target="_blank" style="color:#60a5fa;">';

var MODAL_CONTENT = {
  terms: {
    en: [
      '<p>Please read these Terms of Service carefully before downloading or using GAM Vehicle Editor. By using the Software, you agree to be bound by these Terms.</p>',
      '<h4 '+H4+'>1. Acceptance of Terms</h4>',
      '<p>By downloading, installing, or using GAM Vehicle Editor, you acknowledge that you have read, understood, and agree to these Terms. If you do not agree, do not use the Software.</p>',
      '<h4 '+H4+'>2. License Grant</h4>',
      '<p><strong style="color:#ccc;">Free tier:</strong> We grant you a limited, non-exclusive, non-transferable, revocable license to install and use GAM Vehicle Editor for personal, non-commercial purposes.</p>',
      '<p><strong style="color:#ccc;">Pro / Lifetime license:</strong> Upon purchase of a paid license key, we grant you an upgraded, non-exclusive, non-transferable license to access the full feature set of the Software.</p>',
      '<h4 '+H4+'>3. License Restrictions</h4><p>You may not:</p>',
      '<ul '+UL+'><li>Copy, modify, distribute, sell, or sublicense the Software or its license keys.</li>',
      '<li>Reverse engineer, decompile, or disassemble the Software.</li>',
      '<li>Share your license key with other users or use it on more devices than permitted.</li>',
      '<li>Use the Software for any unlawful purpose or in violation of any third-party terms of service (including game publishers\' terms).</li>',
      '<li>Remove or alter any copyright or proprietary notices in the Software.</li></ul>',
      '<h4 '+H4+'>4. Subscription and Billing</h4>',
      '<p>Pro subscriptions are billed monthly through Lemon Squeezy. You may cancel at any time; your access will continue until the end of the current billing period. We do not offer refunds for partial months.</p>',
      '<p>Lifetime licenses are a one-time purchase with no recurring charges.</p>',
      '<h4 '+H4+'>5. Refund Policy</h4>',
      '<p>We offer refunds within 7 days of purchase if the Software does not function as described and the issue cannot be resolved. Refund requests: '+EMAIL+'</p>',
      '<h4 '+H4+'>6. Disclaimer of Warranties</h4>',
      '<p>THE SOFTWARE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND. We do not guarantee compatibility with all game versions or that modifications will not affect your game installation.</p>',
      '<h4 '+H4+'>7. Limitation of Liability</h4>',
      '<p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOSS OF GAME DATA OR SAVE FILES.</p>',
      '<h4 '+H4+'>8. Game Publisher Compliance</h4>',
      '<p>GAM Vehicle Editor is an independent third-party tool not affiliated with any game publisher. You are responsible for ensuring compliance with the terms of any game you modify.</p>',
      '<h4 '+H4+'>9. Intellectual Property</h4>',
      '<p>GAM Vehicle Editor and all related intellectual property rights are owned by the developer. Nothing in these Terms grants you rights to our trademarks, logos, or other intellectual property.</p>',
      '<h4 '+H4+'>10. Termination</h4>',
      '<p>We reserve the right to terminate or suspend your license at any time if you violate these Terms.</p>',
      '<h4 '+H4+'>11. Updates and Changes</h4>',
      '<p>We may update the Software and these Terms at any time. Continued use constitutes acceptance of the new Terms.</p>',
      '<h4 '+H4+'>12. Contact</h4>',
      '<p>Questions about these Terms: '+EMAIL+'</p>'
    ].join(''),
    zh: [
      '<p>请在下载或使用 GAM Vehicle Editor 之前仔细阅读本服务条款。使用本软件即表示您同意受本条款约束。</p>',
      '<h4 '+H4+'>1. 条款接受</h4>',
      '<p>通过下载、安装或使用 GAM Vehicle Editor，您确认已阅读、理解并同意本条款。如不同意，请勿使用本软件。</p>',
      '<h4 '+H4+'>2. 许可授予</h4>',
      '<p><strong style="color:#ccc;">免费版：</strong>我们授予您有限的、非独占的、不可转让的、可撤销的许可，仅供个人非商业目的安装和使用 GAM Vehicle Editor。</p>',
      '<p><strong style="color:#ccc;">Pro / 终身许可：</strong>购买付费许可证密钥后，我们授予您升级的非独占、不可转让的许可，以访问软件的完整功能集。</p>',
      '<h4 '+H4+'>3. 许可限制</h4><p>您不得：</p>',
      '<ul '+UL+'><li>复制、修改、分发、销售或再许可本软件或其许可证密钥。</li>',
      '<li>对软件进行反向工程、反编译或反汇编。</li>',
      '<li>与其他用户共享您的许可证密钥，或在超出允许数量的设备上使用。</li>',
      '<li>将软件用于任何违法目的，或违反任何第三方服务条款（包括游戏发行商的条款）。</li>',
      '<li>删除或更改软件中的任何版权或专有声明。</li></ul>',
      '<h4 '+H4+'>4. 订阅与计费</h4>',
      '<p>Pro 订阅通过 Lemon Squeezy 按月计费。您可随时取消；您的访问权限将持续到当前计费周期结束。我们不提供不完整月份的退款。</p>',
      '<p>终身许可为一次性购买，无周期性费用。</p>',
      '<h4 '+H4+'>5. 退款政策</h4>',
      '<p>如软件未能按描述运行且问题无法解决，我们在购买后 7 天内提供退款。退款请求请联系：'+EMAIL+'</p>',
      '<h4 '+H4+'>6. 免责声明</h4>',
      '<p>本软件按"现状"提供，不附带任何形式的保证。我们不保证与所有游戏版本的兼容性，也不保证修改不会影响您的游戏安装。</p>',
      '<h4 '+H4+'>7. 责任限制</h4>',
      '<p>在法律允许的最大范围内，我们不对任何间接、附带或后果性损害承担责任，包括游戏数据或存档文件的丢失。</p>',
      '<h4 '+H4+'>8. 游戏发行商合规</h4>',
      '<p>GAM Vehicle Editor 是独立的第三方工具，与任何游戏发行商无关。您有责任确保遵守所修改游戏的条款。</p>',
      '<h4 '+H4+'>9. 知识产权</h4>',
      '<p>GAM Vehicle Editor 及所有相关知识产权归开发者所有。本条款不授予您对我们商标、徽标或其他知识产权的任何权利。</p>',
      '<h4 '+H4+'>10. 终止</h4>',
      '<p>如果您违反本条款，我们保留随时终止或暂停您的许可的权利。</p>',
      '<h4 '+H4+'>11. 更新与变更</h4>',
      '<p>我们可能随时更新软件和本条款。继续使用即表示接受新条款。</p>',
      '<h4 '+H4+'>12. 联系方式</h4>',
      '<p>有关本条款的疑问请联系：'+EMAIL+'</p>'
    ].join(''),
    de: [
      '<p>Bitte lesen Sie diese Nutzungsbedingungen sorgfältig durch, bevor Sie GAM Vehicle Editor herunterladen oder verwenden. Durch die Nutzung der Software stimmen Sie diesen Bedingungen zu.</p>',
      '<h4 '+H4+'>1. Annahme der Bedingungen</h4>',
      '<p>Durch das Herunterladen, Installieren oder Verwenden von GAM Vehicle Editor bestätigen Sie, diese Bedingungen gelesen, verstanden und akzeptiert zu haben. Bei Nichteinverständnis nutzen Sie die Software nicht.</p>',
      '<h4 '+H4+'>2. Lizenzgewährung</h4>',
      '<p><strong style="color:#ccc;">Kostenlos:</strong> Wir gewähren Ihnen eine eingeschränkte, nicht-exklusive, nicht übertragbare, widerrufliche Lizenz zur persönlichen, nicht-kommerziellen Nutzung.</p>',
      '<p><strong style="color:#ccc;">Pro / Lebenslange Lizenz:</strong> Nach dem Kauf eines Lizenzschlüssels erhalten Sie eine erweiterte Lizenz für den vollen Funktionsumfang.</p>',
      '<h4 '+H4+'>3. Lizenzbeschränkungen</h4><p>Sie dürfen nicht:</p>',
      '<ul '+UL+'><li>Die Software oder Lizenzschlüssel kopieren, ändern, verteilen, verkaufen oder weiterlizenzieren.</li>',
      '<li>Die Software zurückentwickeln, dekompilieren oder disassemblieren.</li>',
      '<li>Ihren Lizenzschlüssel mit anderen Nutzern teilen oder auf mehr Geräten als erlaubt verwenden.</li>',
      '<li>Die Software für illegale Zwecke oder gegen Drittanbieter-Nutzungsbedingungen verwenden.</li>',
      '<li>Urheberrechtsvermerke in der Software entfernen oder ändern.</li></ul>',
      '<h4 '+H4+'>4. Abonnement und Abrechnung</h4>',
      '<p>Pro-Abonnements werden monatlich über Lemon Squeezy abgerechnet. Sie können jederzeit kündigen; Ihr Zugang läuft bis Ende des aktuellen Abrechnungszeitraums. Keine anteiligen Rückerstattungen.</p>',
      '<p>Lebenslange Lizenzen sind Einmalkäufe ohne Folgekosten.</p>',
      '<h4 '+H4+'>5. Rückerstattungsrichtlinie</h4>',
      '<p>Wir bieten Rückerstattungen innerhalb von 7 Tagen nach dem Kauf, wenn die Software nicht wie beschrieben funktioniert und das Problem nicht gelöst werden kann. Anfragen an: '+EMAIL+'</p>',
      '<h4 '+H4+'>6. Gewährleistungsausschluss</h4>',
      '<p>Die Software wird "wie besehen" ohne jegliche Gewährleistung bereitgestellt. Wir garantieren keine Kompatibilität mit allen Spielversionen.</p>',
      '<h4 '+H4+'>7. Haftungsbeschränkung</h4>',
      '<p>Im gesetzlich zulässigen Umfang haften wir nicht für indirekte, zufällige oder Folgeschäden, einschließlich Verlust von Spieldaten oder Speicherständen.</p>',
      '<h4 '+H4+'>8. Compliance mit Spieleherstellern</h4>',
      '<p>GAM Vehicle Editor ist ein unabhängiges Tool ohne Zugehörigkeit zu Spieleherstellern. Sie sind verantwortlich für die Einhaltung der jeweiligen Spielbedingungen.</p>',
      '<h4 '+H4+'>9. Geistiges Eigentum</h4>',
      '<p>GAM Vehicle Editor und alle zugehörigen Rechte sind Eigentum des Entwicklers. Diese Bedingungen gewähren kein Recht an Marken, Logos oder anderem geistigen Eigentum.</p>',
      '<h4 '+H4+'>10. Kündigung</h4>',
      '<p>Wir behalten uns das Recht vor, Ihre Lizenz jederzeit zu kündigen oder auszusetzen, wenn Sie gegen diese Bedingungen verstoßen.</p>',
      '<h4 '+H4+'>11. Aktualisierungen</h4>',
      '<p>Wir können die Software und diese Bedingungen jederzeit aktualisieren. Die weitere Nutzung gilt als Zustimmung zu den neuen Bedingungen.</p>',
      '<h4 '+H4+'>12. Kontakt</h4>',
      '<p>Fragen zu diesen Bedingungen: '+EMAIL+'</p>'
    ].join(''),
    ru: [
      '<p>Пожалуйста, внимательно прочитайте настоящие Условия использования перед загрузкой или использованием GAM Vehicle Editor. Используя программное обеспечение, вы соглашаетесь с настоящими Условиями.</p>',
      '<h4 '+H4+'>1. Принятие условий</h4>',
      '<p>Загружая, устанавливая или используя GAM Vehicle Editor, вы подтверждаете, что прочитали, поняли и согласны с настоящими Условиями. Если вы не согласны — не используйте программу.</p>',
      '<h4 '+H4+'>2. Предоставление лицензии</h4>',
      '<p><strong style="color:#ccc;">Бесплатный уровень:</strong> Мы предоставляем вам ограниченную, неисключительную, непередаваемую, отзывную лицензию для личного некоммерческого использования.</p>',
      '<p><strong style="color:#ccc;">Pro / Пожизненная лицензия:</strong> После покупки лицензионного ключа вы получаете расширенную лицензию для доступа ко всем функциям программы.</p>',
      '<h4 '+H4+'>3. Ограничения лицензии</h4><p>Вам запрещается:</p>',
      '<ul '+UL+'><li>Копировать, изменять, распространять, продавать или сублицензировать программу или её лицензионные ключи.</li>',
      '<li>Осуществлять обратное проектирование, декомпиляцию или дизассемблирование программы.</li>',
      '<li>Передавать лицензионный ключ другим пользователям или использовать его на большем числе устройств, чем разрешено.</li>',
      '<li>Использовать программу в незаконных целях или в нарушение условий третьих сторон.</li>',
      '<li>Удалять или изменять уведомления об авторских правах в программе.</li></ul>',
      '<h4 '+H4+'>4. Подписка и оплата</h4>',
      '<p>Подписка Pro оплачивается ежемесячно через Lemon Squeezy. Вы можете отменить подписку в любое время; доступ сохраняется до конца текущего расчётного периода. Возврат за неполные месяцы не производится.</p>',
      '<p>Пожизненные лицензии — единовременная покупка без регулярных платежей.</p>',
      '<h4 '+H4+'>5. Политика возврата</h4>',
      '<p>Мы предоставляем возврат средств в течение 7 дней с момента покупки, если программа не работает как описано и проблема не может быть решена. Запросы: '+EMAIL+'</p>',
      '<h4 '+H4+'>6. Отказ от гарантий</h4>',
      '<p>Программа предоставляется «как есть» без каких-либо гарантий. Мы не гарантируем совместимость со всеми версиями игр.</p>',
      '<h4 '+H4+'>7. Ограничение ответственности</h4>',
      '<p>В максимально допустимой законом степени мы не несём ответственности за косвенный, случайный или последующий ущерб, включая потерю игровых данных или файлов сохранений.</p>',
      '<h4 '+H4+'>8. Соответствие требованиям издателей игр</h4>',
      '<p>GAM Vehicle Editor — независимый инструмент, не связанный ни с одним издателем игр. Вы несёте ответственность за соблюдение условий любой игры, которую вы изменяете.</p>',
      '<h4 '+H4+'>9. Интеллектуальная собственность</h4>',
      '<p>GAM Vehicle Editor и все связанные права интеллектуальной собственности принадлежат разработчику. Настоящие Условия не предоставляют вам прав на торговые марки, логотипы или иную интеллектуальную собственность.</p>',
      '<h4 '+H4+'>10. Прекращение действия</h4>',
      '<p>Мы оставляем за собой право в любое время прекратить или приостановить вашу лицензию в случае нарушения настоящих Условий.</p>',
      '<h4 '+H4+'>11. Обновления и изменения</h4>',
      '<p>Мы можем обновлять программу и настоящие Условия в любое время. Продолжение использования означает согласие с новыми Условиями.</p>',
      '<h4 '+H4+'>12. Контакты</h4>',
      '<p>Вопросы по настоящим Условиям: '+EMAIL+'</p>'
    ].join(''),
    fr: [
      '<p>Veuillez lire attentivement ces Conditions d\'utilisation avant de télécharger ou d\'utiliser GAM Vehicle Editor. En utilisant le Logiciel, vous acceptez d\'être lié par ces Conditions.</p>',
      '<h4 '+H4+'>1. Acceptation des conditions</h4>',
      '<p>En téléchargeant, installant ou utilisant GAM Vehicle Editor, vous reconnaissez avoir lu, compris et accepté ces Conditions. Si vous n\'êtes pas d\'accord, n\'utilisez pas le Logiciel.</p>',
      '<h4 '+H4+'>2. Octroi de licence</h4>',
      '<p><strong style="color:#ccc;">Version gratuite :</strong> Nous vous accordons une licence limitée, non exclusive, non transférable et révocable pour un usage personnel et non commercial.</p>',
      '<p><strong style="color:#ccc;">Licence Pro / À vie :</strong> Après l\'achat d\'une clé de licence payante, vous bénéficiez d\'une licence étendue pour accéder à l\'ensemble des fonctionnalités.</p>',
      '<h4 '+H4+'>3. Restrictions de licence</h4><p>Il vous est interdit de :</p>',
      '<ul '+UL+'><li>Copier, modifier, distribuer, vendre ou sous-licencier le Logiciel ou ses clés de licence.</li>',
      '<li>Procéder à l\'ingénierie inverse, décompiler ou désassembler le Logiciel.</li>',
      '<li>Partager votre clé de licence avec d\'autres utilisateurs ou l\'utiliser sur plus d\'appareils qu\'autorisé.</li>',
      '<li>Utiliser le Logiciel à des fins illégales ou en violation des conditions de service de tiers.</li>',
      '<li>Supprimer ou modifier les mentions de droits d\'auteur dans le Logiciel.</li></ul>',
      '<h4 '+H4+'>4. Abonnement et facturation</h4>',
      '<p>Les abonnements Pro sont facturés mensuellement via Lemon Squeezy. Vous pouvez annuler à tout moment ; votre accès se poursuit jusqu\'à la fin de la période de facturation en cours. Aucun remboursement partiel.</p>',
      '<p>Les licences à vie sont des achats uniques sans frais récurrents.</p>',
      '<h4 '+H4+'>5. Politique de remboursement</h4>',
      '<p>Nous proposons des remboursements dans les 7 jours suivant l\'achat si le Logiciel ne fonctionne pas comme décrit et que le problème ne peut être résolu. Demandes : '+EMAIL+'</p>',
      '<h4 '+H4+'>6. Exclusion de garantie</h4>',
      '<p>Le Logiciel est fourni « en l\'état » sans aucune garantie. Nous ne garantissons pas la compatibilité avec toutes les versions de jeux.</p>',
      '<h4 '+H4+'>7. Limitation de responsabilité</h4>',
      '<p>Dans toute la mesure permise par la loi, nous ne serons pas responsables des dommages indirects, accessoires ou consécutifs, y compris la perte de données de jeu ou de fichiers de sauvegarde.</p>',
      '<h4 '+H4+'>8. Conformité aux éditeurs de jeux</h4>',
      '<p>GAM Vehicle Editor est un outil tiers indépendant, sans affiliation avec aucun éditeur de jeux. Vous êtes responsable du respect des conditions de tout jeu que vous modifiez.</p>',
      '<h4 '+H4+'>9. Propriété intellectuelle</h4>',
      '<p>GAM Vehicle Editor et tous les droits de propriété intellectuelle associés appartiennent au développeur. Ces Conditions ne vous accordent aucun droit sur nos marques, logos ou autre propriété intellectuelle.</p>',
      '<h4 '+H4+'>10. Résiliation</h4>',
      '<p>Nous nous réservons le droit de résilier ou suspendre votre licence à tout moment en cas de violation de ces Conditions.</p>',
      '<h4 '+H4+'>11. Mises à jour et modifications</h4>',
      '<p>Nous pouvons mettre à jour le Logiciel et ces Conditions à tout moment. La poursuite de l\'utilisation vaut acceptation des nouvelles Conditions.</p>',
      '<h4 '+H4+'>12. Contact</h4>',
      '<p>Questions sur ces Conditions : '+EMAIL+'</p>'
    ].join(''),
    es: [
      '<p>Por favor, lea detenidamente estas Condiciones de servicio antes de descargar o usar GAM Vehicle Editor. Al usar el Software, acepta quedar vinculado por estas Condiciones.</p>',
      '<h4 '+H4+'>1. Aceptación de condiciones</h4>',
      '<p>Al descargar, instalar o usar GAM Vehicle Editor, reconoce haber leído, comprendido y aceptado estas Condiciones. Si no está de acuerdo, no use el Software.</p>',
      '<h4 '+H4+'>2. Concesión de licencia</h4>',
      '<p><strong style="color:#ccc;">Versión gratuita:</strong> Le otorgamos una licencia limitada, no exclusiva, intransferible y revocable para uso personal y no comercial.</p>',
      '<p><strong style="color:#ccc;">Licencia Pro / Vitalicia:</strong> Tras la compra de una clave de licencia de pago, obtiene una licencia ampliada para acceder al conjunto completo de funciones.</p>',
      '<h4 '+H4+'>3. Restricciones de licencia</h4><p>No puede:</p>',
      '<ul '+UL+'><li>Copiar, modificar, distribuir, vender o sublicenciar el Software o sus claves de licencia.</li>',
      '<li>Aplicar ingeniería inversa, descompilar o desensamblar el Software.</li>',
      '<li>Compartir su clave de licencia con otros usuarios o usarla en más dispositivos de los permitidos.</li>',
      '<li>Usar el Software para fines ilegales o en violación de los términos de terceros.</li>',
      '<li>Eliminar o alterar los avisos de derechos de autor del Software.</li></ul>',
      '<h4 '+H4+'>4. Suscripción y facturación</h4>',
      '<p>Las suscripciones Pro se facturan mensualmente a través de Lemon Squeezy. Puede cancelar en cualquier momento; su acceso continuará hasta el final del período de facturación. No se ofrecen reembolsos parciales.</p>',
      '<p>Las licencias vitalicias son una compra única sin cargos recurrentes.</p>',
      '<h4 '+H4+'>5. Política de reembolso</h4>',
      '<p>Ofrecemos reembolsos dentro de los 7 días posteriores a la compra si el Software no funciona como se describe y el problema no puede resolverse. Solicitudes: '+EMAIL+'</p>',
      '<h4 '+H4+'>6. Exclusión de garantías</h4>',
      '<p>EL SOFTWARE SE PROPORCIONA "TAL CUAL" SIN GARANTÍA DE NINGÚN TIPO. No garantizamos la compatibilidad con todas las versiones de juegos.</p>',
      '<h4 '+H4+'>7. Limitación de responsabilidad</h4>',
      '<p>EN LA MÁXIMA MEDIDA PERMITIDA POR LA LEY, NO SEREMOS RESPONSABLES DE DAÑOS INDIRECTOS, INCIDENTALES O CONSECUENTES, INCLUIDA LA PÉRDIDA DE DATOS DE JUEGO O ARCHIVOS DE GUARDADO.</p>',
      '<h4 '+H4+'>8. Cumplimiento con editores de juegos</h4>',
      '<p>GAM Vehicle Editor es una herramienta independiente de terceros, sin afiliación con ningún editor de juegos. Usted es responsable de cumplir con los términos de cualquier juego que modifique.</p>',
      '<h4 '+H4+'>9. Propiedad intelectual</h4>',
      '<p>GAM Vehicle Editor y todos los derechos de propiedad intelectual relacionados pertenecen al desarrollador. Estas Condiciones no le otorgan derechos sobre nuestras marcas, logotipos u otra propiedad intelectual.</p>',
      '<h4 '+H4+'>10. Terminación</h4>',
      '<p>Nos reservamos el derecho de terminar o suspender su licencia en cualquier momento si viola estas Condiciones.</p>',
      '<h4 '+H4+'>11. Actualizaciones y cambios</h4>',
      '<p>Podemos actualizar el Software y estas Condiciones en cualquier momento. El uso continuado constituye la aceptación de las nuevas Condiciones.</p>',
      '<h4 '+H4+'>12. Contacto</h4>',
      '<p>Preguntas sobre estas Condiciones: '+EMAIL+'</p>'
    ].join('')
  },
  privacy: {
    en: [
      '<p>GAM Vehicle Editor is committed to protecting your privacy. This Privacy Policy explains what information we collect, how we use it, and your rights.</p>',
      '<h4 '+H4+'>1. Information We Collect</h4>',
      '<ul '+UL+'><li><strong style="color:#ccc;">License key</strong> — Stored locally and transmitted to Lemon Squeezy solely for verification.</li>',
      '<li><strong style="color:#ccc;">Anonymous usage data</strong> — Anonymized, non-personally-identifiable data (editor version, OS version) to improve the product.</li>',
      '<li><strong style="color:#ccc;">Bug reports</strong> — Voluntarily submitted content (game name, issue description, editor version). No personally identifiable information is required or collected.</li></ul>',
      '<h4 '+H4+'>2. Information We Do NOT Collect</h4>',
      '<ul '+UL+'><li>We do not collect your name, email address, or contact information through the editor.</li>',
      '<li>We do not collect your game save files or any game content.</li>',
      '<li>We do not track your in-game activity.</li>',
      '<li>We do not sell or share your data with third parties for advertising purposes.</li></ul>',
      '<h4 '+H4+'>3. License Verification</h4>',
      '<p>License key validation is handled by '+LS_LINK+'. Please refer to their '+LS_PP+'Privacy Policy</a> for details.</p>',
      '<h4 '+H4+'>4. Local Data Storage</h4>',
      '<p>All editor settings, vehicle configurations, and archives are stored locally on your device. We have no access to this data.</p>',
      '<h4 '+H4+'>5. Automatic Updates</h4>',
      '<p>The editor periodically checks for updates via Cloudflare CDN. This includes your editor version and OS type. No personal information is transmitted.</p>',
      '<h4 '+H4+'>6. Third-Party Services</h4>',
      '<ul '+UL+'><li><strong style="color:#ccc;">Lemon Squeezy</strong> — Payment processing and license key management.</li>',
      '<li><strong style="color:#ccc;">Cloudflare</strong> — Website hosting, content delivery, and API infrastructure.</li></ul>',
      '<h4 '+H4+'>7. Data Retention</h4>',
      '<p>Bug report data is retained for up to 12 months for quality improvement purposes, then permanently deleted.</p>',
      '<h4 '+H4+'>8. Your Rights</h4>',
      '<ul '+UL+'><li>Request deletion of any bug report data you submitted.</li>',
      '<li>Opt out of anonymous usage data collection in editor settings (when available).</li></ul>',
      '<p>Contact: '+EMAIL+'</p>',
      '<h4 '+H4+'>9. Children\'s Privacy</h4>',
      '<p>GAM Vehicle Editor is not directed at children under 13. We do not knowingly collect personal information from children.</p>',
      '<h4 '+H4+'>10. Changes to This Policy</h4>',
      '<p>We may update this Privacy Policy from time to time and will post the updated policy with a revised date.</p>',
      '<h4 '+H4+'>11. Contact</h4>',
      '<p>Questions: '+EMAIL+'</p>'
    ].join(''),
    zh: [
      '<p>GAM Vehicle Editor 致力于保护您的隐私。本隐私政策说明我们收集哪些信息、如何使用以及您的权利。</p>',
      '<h4 '+H4+'>1. 我们收集的信息</h4>',
      '<ul '+UL+'><li><strong style="color:#ccc;">许可证密钥</strong> — 本地存储，仅用于向 Lemon Squeezy 进行验证时传输。</li>',
      '<li><strong style="color:#ccc;">匿名使用数据</strong> — 匿名、非个人可识别的数据（编辑器版本、操作系统版本），用于改善产品。</li>',
      '<li><strong style="color:#ccc;">错误报告</strong> — 自愿提交的报告内容（游戏名称、问题描述、编辑器版本）。不要求也不收集个人可识别信息。</li></ul>',
      '<h4 '+H4+'>2. 我们不收集的信息</h4>',
      '<ul '+UL+'><li>我们不通过编辑器收集您的姓名、电子邮件地址或联系方式。</li>',
      '<li>我们不收集您的游戏存档文件或任何游戏内容。</li>',
      '<li>我们不追踪您的游戏内活动。</li>',
      '<li>我们不出售或向第三方共享您的数据用于广告目的。</li></ul>',
      '<h4 '+H4+'>3. 许可证验证</h4>',
      '<p>许可证密钥验证由 '+LS_LINK+' 处理。详情请参阅其 '+LS_PP+'隐私政策</a>。</p>',
      '<h4 '+H4+'>4. 本地数据存储</h4>',
      '<p>所有编辑器设置、车辆配置和存档均存储在您的设备本地。我们无法访问这些数据。</p>',
      '<h4 '+H4+'>5. 自动更新</h4>',
      '<p>编辑器通过 Cloudflare CDN 定期检查更新，包括您的编辑器版本和操作系统类型。不传输个人信息。</p>',
      '<h4 '+H4+'>6. 第三方服务</h4>',
      '<ul '+UL+'><li><strong style="color:#ccc;">Lemon Squeezy</strong> — 支付处理与许可证密钥管理。</li>',
      '<li><strong style="color:#ccc;">Cloudflare</strong> — 网站托管、内容分发与 API 基础设施。</li></ul>',
      '<h4 '+H4+'>7. 数据保留</h4>',
      '<p>错误报告数据保留最多 12 个月用于质量改进，之后永久删除。</p>',
      '<h4 '+H4+'>8. 您的权利</h4>',
      '<ul '+UL+'><li>申请删除您提交的任何错误报告数据。</li>',
      '<li>在编辑器设置中选择退出匿名使用数据收集（如可用）。</li></ul>',
      '<p>联系方式：'+EMAIL+'</p>',
      '<h4 '+H4+'>9. 儿童隐私</h4>',
      '<p>GAM Vehicle Editor 不面向 13 岁以下儿童。我们不会故意收集儿童的个人信息。</p>',
      '<h4 '+H4+'>10. 政策变更</h4>',
      '<p>我们可能不时更新本隐私政策，并发布带有修订日期的更新版本。</p>',
      '<h4 '+H4+'>11. 联系方式</h4>',
      '<p>如有疑问请联系：'+EMAIL+'</p>'
    ].join(''),
    de: [
      '<p>GAM Vehicle Editor ist dem Schutz Ihrer Privatsphäre verpflichtet. Diese Datenschutzrichtlinie erläutert, welche Informationen wir erfassen, wie wir sie verwenden und welche Rechte Sie haben.</p>',
      '<h4 '+H4+'>1. Erfasste Informationen</h4>',
      '<ul '+UL+'><li><strong style="color:#ccc;">Lizenzschlüssel</strong> — Lokal gespeichert und nur zur Verifizierung an Lemon Squeezy übermittelt.</li>',
      '<li><strong style="color:#ccc;">Anonyme Nutzungsdaten</strong> — Anonymisierte, nicht personenbezogene Daten (Editor-Version, OS-Version) zur Produktverbesserung.</li>',
      '<li><strong style="color:#ccc;">Fehlerberichte</strong> — Freiwillig eingereichte Inhalte (Spielname, Problembeschreibung, Editor-Version). Keine personenbezogenen Daten erforderlich.</li></ul>',
      '<h4 '+H4+'>2. Nicht erfasste Informationen</h4>',
      '<ul '+UL+'><li>Wir erfassen nicht Ihren Namen, E-Mail-Adresse oder Kontaktdaten über den Editor.</li>',
      '<li>Wir erfassen keine Spielstände oder Spielinhalte.</li>',
      '<li>Wir verfolgen keine In-Game-Aktivitäten.</li>',
      '<li>Wir verkaufen oder teilen Ihre Daten nicht mit Dritten zu Werbezwecken.</li></ul>',
      '<h4 '+H4+'>3. Lizenzverifizierung</h4>',
      '<p>Die Lizenzschlüsselvalidierung wird von '+LS_LINK+' durchgeführt. Bitte lesen Sie deren '+LS_PP+'Datenschutzrichtlinie</a>.</p>',
      '<h4 '+H4+'>4. Lokale Datenspeicherung</h4>',
      '<p>Alle Editor-Einstellungen, Fahrzeugkonfigurationen und Archive werden lokal auf Ihrem Gerät gespeichert. Wir haben keinen Zugriff auf diese Daten.</p>',
      '<h4 '+H4+'>5. Automatische Updates</h4>',
      '<p>Der Editor prüft regelmäßig auf Updates über Cloudflare CDN, einschließlich Editor-Version und OS-Typ. Keine persönlichen Daten werden übertragen.</p>',
      '<h4 '+H4+'>6. Drittanbieterdienste</h4>',
      '<ul '+UL+'><li><strong style="color:#ccc;">Lemon Squeezy</strong> — Zahlungsabwicklung und Lizenzverwaltung.</li>',
      '<li><strong style="color:#ccc;">Cloudflare</strong> — Website-Hosting, Content Delivery und API-Infrastruktur.</li></ul>',
      '<h4 '+H4+'>7. Datenspeicherung</h4>',
      '<p>Fehlerberichtsdaten werden bis zu 12 Monate zur Qualitätsverbesserung aufbewahrt und dann dauerhaft gelöscht.</p>',
      '<h4 '+H4+'>8. Ihre Rechte</h4>',
      '<ul '+UL+'><li>Beantragen Sie die Löschung von Fehlerberichtsdaten, die Sie eingereicht haben.</li>',
      '<li>Deaktivieren Sie die anonyme Datenerfassung in den Editor-Einstellungen (wenn verfügbar).</li></ul>',
      '<p>Kontakt: '+EMAIL+'</p>',
      '<h4 '+H4+'>9. Kinderdatenschutz</h4>',
      '<p>GAM Vehicle Editor richtet sich nicht an Kinder unter 13 Jahren. Wir erheben wissentlich keine personenbezogenen Daten von Kindern.</p>',
      '<h4 '+H4+'>10. Änderungen dieser Richtlinie</h4>',
      '<p>Wir können diese Datenschutzrichtlinie von Zeit zu Zeit aktualisieren und die aktualisierte Richtlinie mit einem revidierten Datum veröffentlichen.</p>',
      '<h4 '+H4+'>11. Kontakt</h4>',
      '<p>Fragen: '+EMAIL+'</p>'
    ].join(''),
    ru: [
      '<p>GAM Vehicle Editor стремится защитить вашу конфиденциальность. Настоящая Политика конфиденциальности объясняет, какую информацию мы собираем, как используем и каковы ваши права.</p>',
      '<h4 '+H4+'>1. Собираемая информация</h4>',
      '<ul '+UL+'><li><strong style="color:#ccc;">Лицензионный ключ</strong> — Хранится локально и передаётся в Lemon Squeezy исключительно для верификации.</li>',
      '<li><strong style="color:#ccc;">Анонимные данные использования</strong> — Анонимизированные данные (версия редактора, версия ОС) для улучшения продукта.</li>',
      '<li><strong style="color:#ccc;">Отчёты об ошибках</strong> — Добровольно предоставленное содержимое (название игры, описание проблемы, версия редактора). Персональные данные не требуются и не собираются.</li></ul>',
      '<h4 '+H4+'>2. Информация, которую мы НЕ собираем</h4>',
      '<ul '+UL+'><li>Мы не собираем ваше имя, адрес электронной почты или контактную информацию через редактор.</li>',
      '<li>Мы не собираем файлы сохранений или любой игровой контент.</li>',
      '<li>Мы не отслеживаем вашу игровую активность.</li>',
      '<li>Мы не продаём и не передаём ваши данные третьим лицам в рекламных целях.</li></ul>',
      '<h4 '+H4+'>3. Верификация лицензии</h4>',
      '<p>Проверка лицензионных ключей осуществляется через '+LS_LINK+'. Подробности смотрите в их '+LS_PP+'Политике конфиденциальности</a>.</p>',
      '<h4 '+H4+'>4. Локальное хранение данных</h4>',
      '<p>Все настройки редактора, конфигурации транспортных средств и архивы хранятся локально на вашем устройстве. Мы не имеем доступа к этим данным.</p>',
      '<h4 '+H4+'>5. Автоматические обновления</h4>',
      '<p>Редактор периодически проверяет наличие обновлений через Cloudflare CDN, включая версию редактора и тип ОС. Личная информация не передаётся.</p>',
      '<h4 '+H4+'>6. Сторонние сервисы</h4>',
      '<ul '+UL+'><li><strong style="color:#ccc;">Lemon Squeezy</strong> — Обработка платежей и управление лицензионными ключами.</li>',
      '<li><strong style="color:#ccc;">Cloudflare</strong> — Хостинг сайта, доставка контента и API-инфраструктура.</li></ul>',
      '<h4 '+H4+'>7. Хранение данных</h4>',
      '<p>Данные отчётов об ошибках хранятся до 12 месяцев в целях улучшения качества, затем безвозвратно удаляются.</p>',
      '<h4 '+H4+'>8. Ваши права</h4>',
      '<ul '+UL+'><li>Запросить удаление любых данных отчётов об ошибках, которые вы отправили.</li>',
      '<li>Отказаться от сбора анонимных данных использования в настройках редактора (при наличии).</li></ul>',
      '<p>Контакт: '+EMAIL+'</p>',
      '<h4 '+H4+'>9. Конфиденциальность детей</h4>',
      '<p>GAM Vehicle Editor не предназначен для детей до 13 лет. Мы намеренно не собираем личную информацию детей.</p>',
      '<h4 '+H4+'>10. Изменения политики</h4>',
      '<p>Мы можем периодически обновлять настоящую Политику конфиденциальности и публиковать обновлённую версию с пересмотренной датой.</p>',
      '<h4 '+H4+'>11. Контакты</h4>',
      '<p>Вопросы: '+EMAIL+'</p>'
    ].join(''),
    fr: [
      '<p>GAM Vehicle Editor s\'engage à protéger votre vie privée. Cette Politique de confidentialité explique les informations que nous collectons, comment nous les utilisons et vos droits.</p>',
      '<h4 '+H4+'>1. Informations collectées</h4>',
      '<ul '+UL+'><li><strong style="color:#ccc;">Clé de licence</strong> — Stockée localement et transmise à Lemon Squeezy uniquement pour vérification.</li>',
      '<li><strong style="color:#ccc;">Données d\'utilisation anonymes</strong> — Données anonymisées non identifiables personnellement (version de l\'éditeur, version OS) pour améliorer le produit.</li>',
      '<li><strong style="color:#ccc;">Rapports de bugs</strong> — Contenu soumis volontairement (nom du jeu, description du problème, version de l\'éditeur). Aucune information personnelle n\'est requise ou collectée.</li></ul>',
      '<h4 '+H4+'>2. Informations non collectées</h4>',
      '<ul '+UL+'><li>Nous ne collectons pas votre nom, adresse e-mail ou informations de contact via l\'éditeur.</li>',
      '<li>Nous ne collectons pas vos fichiers de sauvegarde ou tout contenu de jeu.</li>',
      '<li>Nous ne suivons pas votre activité en jeu.</li>',
      '<li>Nous ne vendons ni ne partageons vos données avec des tiers à des fins publicitaires.</li></ul>',
      '<h4 '+H4+'>3. Vérification de licence</h4>',
      '<p>La validation des clés de licence est gérée par '+LS_LINK+'. Veuillez consulter leur '+LS_PP+'Politique de confidentialité</a> pour plus de détails.</p>',
      '<h4 '+H4+'>4. Stockage local des données</h4>',
      '<p>Tous les paramètres de l\'éditeur, configurations de véhicules et archives sont stockés localement sur votre appareil. Nous n\'avons pas accès à ces données.</p>',
      '<h4 '+H4+'>5. Mises à jour automatiques</h4>',
      '<p>L\'éditeur vérifie périodiquement les mises à jour via Cloudflare CDN, incluant la version de l\'éditeur et le type d\'OS. Aucune information personnelle n\'est transmise.</p>',
      '<h4 '+H4+'>6. Services tiers</h4>',
      '<ul '+UL+'><li><strong style="color:#ccc;">Lemon Squeezy</strong> — Traitement des paiements et gestion des clés de licence.</li>',
      '<li><strong style="color:#ccc;">Cloudflare</strong> — Hébergement, distribution de contenu et infrastructure API.</li></ul>',
      '<h4 '+H4+'>7. Conservation des données</h4>',
      '<p>Les données des rapports de bugs sont conservées jusqu\'à 12 mois à des fins d\'amélioration de la qualité, puis définitivement supprimées.</p>',
      '<h4 '+H4+'>8. Vos droits</h4>',
      '<ul '+UL+'><li>Demander la suppression de toute donnée de rapport de bug que vous avez soumise.</li>',
      '<li>Se désinscrire de la collecte de données d\'utilisation anonymes dans les paramètres de l\'éditeur (si disponible).</li></ul>',
      '<p>Contact : '+EMAIL+'</p>',
      '<h4 '+H4+'>9. Confidentialité des enfants</h4>',
      '<p>GAM Vehicle Editor n\'est pas destiné aux enfants de moins de 13 ans. Nous ne collectons pas sciemment d\'informations personnelles auprès des enfants.</p>',
      '<h4 '+H4+'>10. Modifications de cette politique</h4>',
      '<p>Nous pouvons mettre à jour cette Politique de confidentialité de temps en temps et publier la politique mise à jour avec une date révisée.</p>',
      '<h4 '+H4+'>11. Contact</h4>',
      '<p>Questions : '+EMAIL+'</p>'
    ].join(''),
    es: [
      '<p>GAM Vehicle Editor se compromete a proteger su privacidad. Esta Política de privacidad explica qué información recopilamos, cómo la usamos y sus derechos.</p>',
      '<h4 '+H4+'>1. Información que recopilamos</h4>',
      '<ul '+UL+'><li><strong style="color:#ccc;">Clave de licencia</strong> — Almacenada localmente y transmitida a Lemon Squeezy únicamente para verificación.</li>',
      '<li><strong style="color:#ccc;">Datos de uso anónimos</strong> — Datos anonimizados no identificables personalmente (versión del editor, versión del SO) para mejorar el producto.</li>',
      '<li><strong style="color:#ccc;">Informes de errores</strong> — Contenido enviado voluntariamente (nombre del juego, descripción del problema, versión del editor). No se requiere ni recopila información personal identificable.</li></ul>',
      '<h4 '+H4+'>2. Información que NO recopilamos</h4>',
      '<ul '+UL+'><li>No recopilamos su nombre, dirección de correo electrónico ni información de contacto a través del editor.</li>',
      '<li>No recopilamos sus archivos de guardado ni ningún contenido del juego.</li>',
      '<li>No rastreamos su actividad dentro del juego.</li>',
      '<li>No vendemos ni compartimos sus datos con terceros con fines publicitarios.</li></ul>',
      '<h4 '+H4+'>3. Verificación de licencia</h4>',
      '<p>La validación de claves de licencia es gestionada por '+LS_LINK+'. Consulte su '+LS_PP+'Política de privacidad</a> para más detalles.</p>',
      '<h4 '+H4+'>4. Almacenamiento local de datos</h4>',
      '<p>Toda la configuración del editor, las configuraciones de vehículos y los archivos se almacenan localmente en su dispositivo. No tenemos acceso a estos datos.</p>',
      '<h4 '+H4+'>5. Actualizaciones automáticas</h4>',
      '<p>El editor verifica periódicamente las actualizaciones a través de Cloudflare CDN, incluyendo la versión del editor y el tipo de SO. No se transmite información personal.</p>',
      '<h4 '+H4+'>6. Servicios de terceros</h4>',
      '<ul '+UL+'><li><strong style="color:#ccc;">Lemon Squeezy</strong> — Procesamiento de pagos y gestión de claves de licencia.</li>',
      '<li><strong style="color:#ccc;">Cloudflare</strong> — Alojamiento web, entrega de contenido e infraestructura API.</li></ul>',
      '<h4 '+H4+'>7. Retención de datos</h4>',
      '<p>Los datos de informes de errores se conservan hasta 12 meses con fines de mejora de calidad y luego se eliminan permanentemente.</p>',
      '<h4 '+H4+'>8. Sus derechos</h4>',
      '<ul '+UL+'><li>Solicitar la eliminación de cualquier dato de informe de errores que haya enviado.</li>',
      '<li>Optar por no participar en la recopilación de datos de uso anónimos en la configuración del editor (cuando esté disponible).</li></ul>',
      '<p>Contacto: '+EMAIL+'</p>',
      '<h4 '+H4+'>9. Privacidad de los niños</h4>',
      '<p>GAM Vehicle Editor no está dirigido a niños menores de 13 años. No recopilamos conscientemente información personal de niños.</p>',
      '<h4 '+H4+'>10. Cambios en esta política</h4>',
      '<p>Podemos actualizar esta Política de privacidad de vez en cuando y publicar la política actualizada con una fecha revisada.</p>',
      '<h4 '+H4+'>11. Contacto</h4>',
      '<p>Preguntas: '+EMAIL+'</p>'
    ].join('')
  }
};
